name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The name of the tag for the release'
        required: true
        default: 'v1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: dist/main.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-build
        path: dist/main

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Download Windows build
      uses: actions/download-artifact@v2
      with:
        name: windows-build
        path: ./build

    - name: Download macOS build
      uses: actions/download-artifact@v2
      with:
        name: macos-build
        path: ./build

    - name: Create a tag
      id: create_tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ github.event.inputs.tag_name }}
        git push origin ${{ github.event.inputs.tag_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/*
        tag_name: ${{ github.event.inputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
